{"name": "test_order_api", "status": "failed", "statusDetails": {"message": "AssertionError", "trace": "self = <scripts.testOrder.TestOrderApi object at 0x000002C1A26CA3C8>\n\n    def test_order_api(self):\n        \"\"\"创建订单\"\"\"\n        # 商品id\n        product_id = 7\n        # 购买数量\n        count = 3\n        # 响应对象\n        res = ApiFactory.get_order_api().create_order_api(product_id, count)\n        # 打印 请求地址 打印请求参数 打印请求响应数据\n        logging.info(\"请求地址：{}\".format(res.url))\n        logging.info(f\"响应数据：{res.json()}\")\n        # 断言 状态码\n>       utils.common_assert_code(res)\n\nscripts\\testOrder.py:38: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nres = <Response [401]>, code = 200\n\n    def common_assert_code(res, code=200):\n        \"\"\"\n        通用断言状态码\n        :param res: 响应对象\n        :param code200: 状态码 默认值200\n        :return:\n        \"\"\"\n>       assert res.status_code == code\nE       AssertionError\n\nutils.py:8: AssertionError"}, "description": "创建订单", "attachments": [{"name": "log", "source": "74d26281-1f40-4960-9480-c5c22e0ca7a5-attachment.txt", "type": "text/plain"}], "start": 1602559728656, "stop": 1602559728678, "uuid": "bae0cb5b-7b25-4430-802e-aa8eca4c6b7a", "historyId": "d83ccc78fa016d948660518e2c2be922", "testCaseId": "c038ce2d687ad761b69a1f7b904f32a0", "fullName": "scripts.testOrder.TestOrderApi#test_order_api", "labels": [{"name": "parentSuite", "value": "scripts"}, {"name": "suite", "value": "testOrder"}, {"name": "subSuite", "value": "TestOrderApi"}, {"name": "host", "value": "DESKTOP-7793Q7A"}, {"name": "thread", "value": "19652-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "scripts.testOrder"}]}