{"name": "test_user_address_api", "status": "failed", "statusDetails": {"message": "AssertionError", "trace": "self = <scripts.testUser.TestUserApi object at 0x0000011A58F8DE10>\n\n    def test_user_address_api(self):\n        # 响应对象\n        res = ApiFactory.get_user_api().user_address_api()\n        # 打印 请求地址 打印请求参数 打印请求响应数据\n        logging.info(\"请求地址：{}\".format(res.url))\n        logging.info(f\"响应数据：{res.json()}\")\n        # 断言状态码\n        # assert res.status_code == 200\n>       utils.common_assert_code(res)\n\nscripts\\testUser.py:44: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nres = <Response [401]>, code = 200\n\n    def common_assert_code(res, code=200):\n        \"\"\"\n        通用断言状态码\n        :param res: 响应对象\n        :param code200: 状态码 默认值200\n        :return:\n        \"\"\"\n>       assert res.status_code == code\nE       AssertionError\n\nutils.py:8: AssertionError"}, "attachments": [{"name": "log", "source": "a3c7cbad-554e-40c7-81d4-65a48cd3adc4-attachment.txt", "type": "text/plain"}], "start": 1602559578527, "stop": 1602559578553, "uuid": "dcddbc1d-82ca-4c8b-9254-a3037a3f3d61", "historyId": "679af9dd0e21680289c04e4704f824a2", "testCaseId": "282e3cb48c4213c6dd0673cd5e9c98ab", "fullName": "scripts.testUser.TestUserApi#test_user_address_api", "labels": [{"name": "tag", "value": "run(code=0)"}, {"name": "parentSuite", "value": "scripts"}, {"name": "suite", "value": "testUser"}, {"name": "subSuite", "value": "TestUserApi"}, {"name": "host", "value": "DESKTOP-7793Q7A"}, {"name": "thread", "value": "10836-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "scripts.testUser"}]}